---
version: "3.7"

services:

  rails:
    build:
      context: .
      args:
        APP_NAME: $APP_NAME
        RAILS_DATABASE_ENGINE: $RAILS_DATABASE_ENGINE
        RAILS_VERSION: $RAILS_VERSION
        SKIP_TEST_UNIT: $SKIP_TEST_UNIT
        VIEW_ENGINE: $VIEW_ENGINE
    command: rails s -p 3000 -b "0.0.0.0"
    container_name: rails
    env_file: ./.env
    image: "${APP_NAME}:0.1.0"
    ports:
      - 8777:3000
    volumes:
      - .:/srv/$APP_NAME
      - rails_bundle_data:/usr/local/bundle

  mysql:
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    container_name: postgres
    image: postgres:11.3
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgres/data

volumes:
  rails_bundle_data:
  mysql_data:
  postgres_data:
